name: tatlacas_authentication
description: TatlaCas Authentication
version: 1.0.1
publish_to: none
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  tatlacas_sqflite_storage:
    git:
      url: git@github.com:tatlacas-com/tatlacas_sqflite_storage.git
      ref: main
  tatlacas_flutter_oauth:
    git:
      url: git@github.com:tatlacas-com/tatlacas_flutter_oauth.git
      ref: main

  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  sqflite: ^2.0.1
  uuid: ^3.0.5
  path_provider: ^2.0.8
  universal_platform: ^1.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  bloc_test: ^9.0.1
  build_runner:
  test:

flutter: