name: ndaza_authentication
description: Ndaza Authentication
version: 0.0.1
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  tatlacas_sql_storage:
    path: ../tatlacas_sql_storage
  tatlacas_flutter_oauth:
    path: ../tatlacas_flutter_oauth

  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.2
  sqflite: ^2.0.0+2
  uuid: ^3.0.1
  path_provider: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  bloc_test: ^8.0.2
  build_runner:
  test:

flutter: