name: ndaza_authentication
description: Ndaza Authentication
version: 0.0.1
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  tatlacas_sqflite_storage:
    path: ../tatlacas_sqflite_storage
  tatlacas_flutter_oauth:
    path: ../tatlacas_flutter_oauth

  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  sqflite: ^2.0.1
  uuid: ^3.0.5
  path_provider: ^2.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  bloc_test: ^9.0.1
  build_runner:
  test:

flutter: