name: ndaza_authentication
description: Ndaza Authentication
version: 0.0.1
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.2

  ndaza_user_repository:
    path: ndaza_user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  bloc_test: ^8.0.2
  build_runner:
  test:

flutter: