// Mocks generated by Mockito 5.0.9 from annotations
// in ndaza_authentication/test/blocs/oauth_login/oauth_login_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:bloc/src/bloc.dart' as _i6;
import 'package:bloc/src/transition.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ndaza_authentication/src/blocs/authentication/authentication_bloc.dart'
    as _i2;
import 'package:ndaza_user_repository/src/models/user_entity.dart' as _i4;
import 'package:ndaza_user_repository/src/user_repository.dart' as _i7;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeAuthenticationState extends _i1.Fake
    implements _i2.AuthenticationState {}

class _FakeStreamSubscription<T> extends _i1.Fake
    implements _i3.StreamSubscription<T> {}

class _FakeUserEntity extends _i1.Fake implements _i4.UserEntity {}

/// A class which mocks [AuthenticationBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationBloc extends _i1.Mock
    implements _i2.AuthenticationBloc {
  MockAuthenticationBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthenticationState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeAuthenticationState()) as _i2.AuthenticationState);
  @override
  _i3.Stream<_i2.AuthenticationState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i2.AuthenticationState>.empty())
          as _i3.Stream<_i2.AuthenticationState>);
  @override
  _i3.Stream<_i2.AuthenticationState> mapEventToState(
          _i2.AuthenticationEvent? event) =>
      (super.noSuchMethod(Invocation.method(#mapEventToState, [event]),
              returnValue: Stream<_i2.AuthenticationState>.empty())
          as _i3.Stream<_i2.AuthenticationState>);
  @override
  void add(_i2.AuthenticationEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i2.AuthenticationEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<_i5.Transition<_i2.AuthenticationEvent, _i2.AuthenticationState>>
      transformEvents(
              _i3.Stream<_i2.AuthenticationEvent>? events,
              _i6.TransitionFunction<_i2.AuthenticationEvent, _i2.AuthenticationState>?
                  transitionFn) =>
          (super.noSuchMethod(
                  Invocation.method(#transformEvents, [events, transitionFn]),
                  returnValue:
                      Stream<_i5.Transition<_i2.AuthenticationEvent, _i2.AuthenticationState>>.empty())
              as _i3.Stream<
                  _i5.Transition<_i2.AuthenticationEvent, _i2.AuthenticationState>>);
  @override
  void emit(_i2.AuthenticationState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i5.Transition<_i2.AuthenticationEvent, _i2.AuthenticationState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<_i5.Transition<_i2.AuthenticationEvent, _i2.AuthenticationState>>
      transformTransitions(
              _i3.Stream<_i5.Transition<_i2.AuthenticationEvent, _i2.AuthenticationState>>?
                  transitions) =>
          (super.noSuchMethod(
                  Invocation.method(#transformTransitions, [transitions]),
                  returnValue:
                      Stream<_i5.Transition<_i2.AuthenticationEvent, _i2.AuthenticationState>>.empty())
              as _i3.Stream<
                  _i5.Transition<_i2.AuthenticationEvent, _i2.AuthenticationState>>);
  @override
  _i3.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future.value()) as _i3.Future<void>);
  @override
  _i3.StreamSubscription<_i2.AuthenticationState> listen(
          void Function(_i2.AuthenticationState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription<_i2.AuthenticationState>())
          as _i3.StreamSubscription<_i2.AuthenticationState>);
  @override
  void onChange(_i5.Change<_i2.AuthenticationState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i7.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.UserEntity> saveUser(_i4.UserEntity? user) =>
      (super.noSuchMethod(Invocation.method(#saveUser, [user]),
              returnValue: Future<_i4.UserEntity>.value(_FakeUserEntity()))
          as _i3.Future<_i4.UserEntity>);
  @override
  _i3.Future<_i4.UserEntity?> getUser() =>
      (super.noSuchMethod(Invocation.method(#getUser, []),
              returnValue: Future<_i4.UserEntity?>.value())
          as _i3.Future<_i4.UserEntity?>);
}
